<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMcRvBsa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMcRvBsa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMcRvBsa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMcRvBsa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMcRvBsa\App_KernelDevDebugContainer([
    'container.build_hash' => 'McRvBsa',
    'container.build_id' => 'a95a5171',
    'container.build_time' => 1764156054,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMcRvBsa');
